### ISSUE TITLE
Expose autocompletion within civiCRM profile

### ISSUE THREAD

**Issue by larnoult** [allinappli/frenchCodePost-civicrm#1]
Thanks for this great add-on!
Would be great to be able to expose this field within the profile, so users can autocomplete their adress while completing a form 🙏

**Comment by wyde22** [comment]
Pour bien comprendre, vous voulez ajouter le champ de calcul de l'adresse dans un profil CiviCRM

![Modifier-M-Peter-Parker-‹-dewy2-dev-inoede-symbiodev-xyz-—-WordPress](https://github.com/user-attachments/assets/2250070e-f228-4aba-9714-6a753f51921e)

![Champs-de-profil-CiviCRM-Vos-informations-d-inscription-‹-dewy2-dev-inoede-symbiodev-xyz-—-WordPress](https://github.com/user-attachments/assets/082623a6-a0ad-41ed-9f9c-d935a88b300e)

**Comment by dev-allinappli** [comment]
oui tout à fait. la question qui se pose c'est si est-ce que ce champ spécial est en mesure ensuite de mettre à jour l'adresse du contact même si les 3 champs impliqués adresse, code postal et ville ne sont pas ajoutés au profil ?

**Comment by dev-allinappli** [comment]
jusqu'à présent nous utilisions du JS pour cacher le bloc adresse et afficher le nouveau champ mais le bloc adresse existait bien dans la page. Les profils fonctionnent différemment si tu vois ce que je veux dire. Les champs 'adresse', 'code postal' et 'ville' sont complètement indépendants, ils n'appartiennent pas à une entité type 'adresse complète'.
mais peut-être que ta méthode est fonctionnelle

**Comment by wyde22** [comment]
j'ai développé une première approche en proposant un champ personnalisé de type text. Ce champ pourra être ajouté dans un profil aisément. Ce champ personnalisé sera encapsulé dans l'extension via un managed

l'idée est de garder au maximum l'existant et essayer de faire fonctionner la recherche d'adresse. J'ai réussi à faire ça : 

![TEST-–-dewy2-dev-inoede-symbiodev-xyz](https://github.com/user-attachments/assets/fee62c80-b297-4331-bccf-a39a11b6fb12)

ensuite je dois gérer le submit du form via le `hook_civicrm_postProcess` en récupérant les valeurs du champ pour implémenter le champ rue, ville, pays subdivision, code postal. Voici ce que j'ai dans l'objet `form` à la soumission du formulaire : 
```
[6]=>
    object(HTML_QuickForm_text)#2480 (9) {
      ["_attributes"]=>
      array(5) {
        ["data-crm-custom"]=>
        string(47) "Champ_codes_postaux_France:Saisie_adresse_input"
        ["maxlength"]=>
        int(255)
        ["name"]=>
        string(9) "custom_47"
        ["type"]=>
        string(4) "text"
        ["value"]=>
        string(96) "Bordeaux / 33000 / Place Marie Brizard / 33, Gironde, Nouvelle-Aquitaine / 416770.3 / 6423213.32"
      }
```

je vais parser le paramètre `["value"]` de cet objet

je te tiens au courant

**Comment by dev-allinappli** [comment]
ah super, ça s'annonce bien ! le nouveau champ texte personnalisé 'auto-complétion d'adresse' sera créé par l'extension lors de l'activation ?

**Comment by wyde22** [comment]
je fais comme ça dorénavant avec mes extensions civicrm. J'encapsule le maximum de choses dans des managed (SK, FB, profil, listes, champs personnalisés, etc ...)

a l'activation de l'extension et en vidant les caches le champ personnalisé sera à la disposition du projet

**Comment by dev-allinappli** [comment]
ok super, est-il possible lors de l'activation de l'extension de forcer le vidage du cache ? avec une commande de ce genre 

```
$results = civicrm_api4('System', 'flush', [
  'checkPermissions' => TRUE,
]);
```

**Comment by wyde22** [comment]
> ok super, est-il possible lors de l'activation de l'extension de forcer le vidage du cache ? avec une commande de ce genre

je ne sais pas si c'est possible. Mais je pense qu'à l'activation de l'extension, civicrm vide les caches. A tester

du coup je reviens vers toi pour te partager par écrit ce que j'ai fait. Le but du développement était d'utiliser au maximum l'existant et la logique actuelle de l'extension.
j'ai ajouté un champ personnalisé texte dans un ensemble de champ perso. Cet ensemble et ce champ est mis dans un managed pour faciliter le déploiement de ce genre de fonctionnalités.

ensuite on a un champ perso qu'on peut utiliser dans un profil. ce champ possède un identifiant est une caractéristique précise qui se trouve dans le managed. Je dois récupérer les infos de ce champ personnalisé. J'utilise le name du champ perso pour récupérer les données. via du code javascript j'ajoute le bon identifiant sur le champ perso afin que la logique de calcul d'adresse se fasse correctement avec le code existant.

a la soumission du formulaire je récupère l'identifiant du contact en utilisant l'email inscrit dans le profil. Avec cet identifiant je fais une vérification sur les adresses présentes ou non pour le contact. Si il n'y a pas d'adresse j'en créé une de type principale. Si non j'ajoute une nouvelle adresse de type autre.

voici mes questions : 
- pour un fonctionnement optimal de cette fonctionnalité je pense qu'il faut utiliser le profil en mode `create`. 
- pour un profil en mode `edit`, je n'ai pas trouvé de solution robuste de récupérer le bon identifiant du contact présent dans le formulaire. Je le fait via une adresse email. Idéalement on devrait récupérer l'identifiant du contact
- pour mes tests, j'ai créé un ensemble de champs personnalisés pour l'entité Contact. J'ai fait mes tests avec un contact de type individu. A tester sur un contact de type organisation si cela fonctionne correctement
- d'ailleurs je me demande si ce n'est pas préférable de créer un profil dédié (encapsulé dans un managed) et protégé avec les champs nécessaires pour faire le calcul d'adresse. a voir ensemble
mon travail se trouve sur le branche [travail-fieldapiban-profile](https://github.com/ALLINAPPLI/frenchCodePost-civicrm/tree/travail-fieldapiban-profile)

**Comment by wyde22** [comment]
suite à notre entrevue cet après midi j'ai revu un peu le code. 
- j'ai encapsulé le profil dans un managed
- j'ai revu le traitement afin qu'a la sélection d'une adresse dans le champ API BAN cela change les valeurs dans les champs adresses du profil
- ça simplifie un peu le code car on est sur des champs civicrm natif. du coup le soumission se fait plus aisément. J'ai fait un peu le ménage dans mon code

**Comment by dev-allinappli** [comment]
peux-tu pousser sur GitHub pour que je puisse tester (si c'est fonctionnel bien sûr) ?

**Comment by wyde22** [comment]
@allinappliadmin tout le code est poussé sur la branche suivante : `travail-fieldapiban-profile`. J'ai enlevé le code qui gérait le traitement au postProcess du formulaire. 

donc il faut faire un checkout sur la branche et ensuite vider les caches civicrm afin que le profil puisse être pris en compte par ton CRM

N'hésites pas à revenir vers moi si besoin

**Comment by dev-allinappli** [comment]
j'ai une erreur à la console que je pense liée à l'extension. ça te parle :
```
In Utils.php line 23:
                              
  Class "WP_Roles" not found  
```

**Comment by dev-allinappli** [comment]
cloné

![image](https://github.com/user-attachments/assets/9fd3190c-b6e4-46f5-9134-7418d9b5e2d4)

**Comment by dev-allinappli** [comment]
ça fonctionne bien dans la synthèse du contact

![image](https://github.com/user-attachments/assets/3639305a-461a-4477-bfb7-96b81394ead5)

**Comment by dev-allinappli** [comment]
en revanche, ça ne fonctionne pas dans un profil pour une adhésion (https://testwpcivi.appli.in/civicrm/contribute/transact/?reset=1&id=1)

![image](https://github.com/user-attachments/assets/a14a83c2-6520-47f8-96cc-28dc99eddc9f)

**Comment by wyde22** [comment]
> j'ai une erreur à la console que je pense liée à l'extension. ça te parle :

In Utils.php line 23:
                              
  Class "WP_Roles" not found  

bizarre je ne fais pas appel à cette classe dans mon code à la ligne 23. Cela doit provenir d'une autre extension ?

**Comment by dev-allinappli** [comment]
> > j'ai une erreur à la console que je pense liée à l'extension. ça te parle :
> 
> In Utils.php line 23:
> 
> Class "WP_Roles" not found
> 
> bizarre je ne fais pas appel à cette classe dans mon code à la ligne 23. Cela doit provenir d'une autre extension ?

probablement l'extension de synchronisation groupe/rôle non ?

**Comment by wyde22** [comment]
> en revanche, ça ne fonctionne pas dans un profil pour une adhésion (https://testwpcivi.appli.in/civicrm/contribute/transact/?reset=1&id=1)

ok je comprends le script js n'est pas chargée sur les pages contribution. Je vais faire le nécessaire et revenir vers toi par la suite

**Comment by dev-allinappli** [comment]
d'accord. dans ce cas, il faut que le profil soit chargé là où il pourra l'être : event, adhésion, contribution

**Comment by wyde22** [comment]
je viens d'apporter une correction pour faire fonctionner le script sur les formulaires de contribution. En fait dans le code il faut ajouter le script js via le `hook_civicrm_buildForm` et le template smarty via le `hook_civicrm_alterContent`

**Comment by dev-allinappli** [comment]
je peux mettre à jour ?

**Comment by dev-allinappli** [comment]
je l'ai fait - sûrement trop vite. j'ai cette erreur `Unable to load template 'file:CRM/postcode_profile.tpl'`

**Comment by dev-allinappli** [comment]
```
In frenchcodepostaux.php line 143:
                                                                        
  Call to undefined function _frenchcodepostaux_civix_civicrm_themes()  
```

**Comment by wyde22** [comment]
oui c'est bon j'ai revu un peu mon code pour simplifier les appels du script js et du template smarty sur la branche. tu peux refaire un pull stp ?

**Comment by dev-allinappli** [comment]
> oui c'est bon j'ai revu un peu mon code pour simplifier les appels du script js et du template smarty sur la branche. tu peux refaire un pull stp ?

j'ai bien l'erreur spécifiée juste au-dessus

**Comment by wyde22** [comment]
est ce que tu peux vider le cache civicrm stp ?

**Comment by dev-allinappli** [comment]
caches Civi et WP vidés et j'ai toujours l'erreur

**Comment by wyde22** [comment]
est ce possible d'avoir les accès à ton site de test stp ?

**Comment by wyde22** [comment]
> caches Civi et WP vidés et j'ai toujours l'erreur

tu as cette erreur sur la page de contribution ? j'ai revu mon découpage dans le code. est ce que tu peux vérifier stp ?

**Comment by dev-allinappli** [comment]
c'est vraiment bizarre car j'ai tout nettoyé et supprimer dont le profil et quand je le réinstalle et que j'active l'extension je ne l'ai plus :-/

**Comment by wyde22** [comment]
je crois savoir d'ou vient le problème. La version de smarty n'a pas l'air de reconnaître l'appel au template. Il faut je fasse un civix upgrade mais cela ne fonctionne pas. Je te créée un ticket pour ça

**Comment by dev-allinappli** [comment]
je viens de faire civix upgrade

**Comment by dev-allinappli** [comment]
ça marche nickel dans le résumé de contact, la page de profil wordpress et l'adhésion en ligne

**Comment by wyde22** [comment]
> je viens de faire civix upgrade

> ça marche nickel dans le résumé de contact, la page de profil wordpress et l'adhésion en ligne

ok j'avais créer une branche spécifique pour cet upgrade. Je regarde les fichiers modifiés et je merge dans master. Je te tiens au courant

**Comment by dev-allinappli** [comment]
ok merci.

**Comment by wyde22** [comment]
tout a été mis sur la branche master. cela à l'air de mieux fonctionner maintenant. J'ai un peu galéré avec la gestion des branches sur le serveur...je te poserais quelques questions à l'occasion afin de bien comprendre comment git fonctionne sur vos machines :)

**Comment by dev-allinappli** [comment]
c'est moi ou il ne fonctionne plus ? https://testwpcivi.appli.in/wp-admin/admin.php?page=CiviCRM&q=civicrm%2Fcontribute%2Ftransact&reset=1&id=1

![image](https://github.com/user-attachments/assets/a69347f0-f73c-4ff0-9ace-64aba5e3e59d)

**Comment by wyde22** [comment]
ce formulaire est généré dans civicrm, du coup la structure HTML change un peu et le code js ne retrouve pas ces petits pour ajouter la valeur par défaut.

cependant, avec Guy, on fait autrement quand on veut exposer un formulaire civicrm dans WP. On utilise beaucoup les shortcodes. Le gros avantage de cette pratique est que les urls sont plus lisibles et user friendly. Voici  ci dessous un exemple : 

![Edition-de-mon-profil-–-Base-test-ALL-IN-APPLI-09-26-2024_01_05_PM](https://github.com/user-attachments/assets/cd08cc97-1062-4316-adff-da2df745675a)

les pages shortcodes fonctionnent correctement

je vais quand même voir plus en profondeur ce problème d'utilisation de cette fonctionnalité dans civicrm

**Comment by dev-allinappli** [comment]
je comprends cet intérêt pour les short codes néanmoins il y a actuellement une majorité de sites sous Drupal 7 et cela ne fonctionnerait pas. Il me semble important que l'extension soit agnostique du point de vue du CMS, surtout avec Standalone en perspective.

**Comment by wyde22** [comment]
> je comprends cet intérêt pour les short codes néanmoins il y a actuellement une majorité de sites sous Drupal 7 et cela ne fonctionnerait pas. Il me semble important que l'extension soit agnostique du point de vue du CMS, surtout avec Standalone en perspective.

ok je comprends.

dans mon code je souhaitais que l'API BAN fonctionne uniquement sur le front d'un CMS. J'ai enlevé cette condition et maintenant cela fonctionne dans les profils encapsulés dans un shortcode et également via un lien.

pour info je garde encore une condition : je recherche le champ personnalisé encapsulé dans cette extension. Si ce champ n'est pas trouvé l'API BAN ne se lance pas.

Sur la page d'accueil de ce site de test, j'ai mis à ta disposition 3 liens : un lien vers un shortcode contribution, un lien vers un shortcode édition de profil et un lien vers un formulaire civicrm

A tester plus globalement avec un cms drupal et sur l'instance standalone

**Comment by dev-allinappli** [comment]
> pour info je garde encore une condition : je recherche le champ personnalisé encapsulé dans cette extension. Si ce champ n'est pas trouvé l'API BAN ne se lance pas.

oui c'est tout à fait normal

**Comment by dev-allinappli** [comment]
je viens de tester c'est sur la testwpcivi, c'est génial

**Comment by dev-allinappli** [comment]
peux-tu enlever le texte redondant 'entrer une ville ou un code postal'

![image](https://github.com/user-attachments/assets/84e0de56-5a75-48b4-bacf-b725578e74d8)

**Comment by wyde22** [comment]
ok je viens d'enlever la mention

**Comment by dev-allinappli** [comment]
merci

**Comment by wyde22** [comment]
ma suppression de ma condition a été brutale. Il faut la garder, mais cette fois ci je cherche le champ personnalisé API BAN dans le bon profil. J'ai pu remarquer que le name du profil encapsulé dans l'extension est mis en tant que class css dans le HTML. Je fais une recherche en se basant dessus afin d'appliquer l'effet js API BAN sur les profils.

la modification dans la fiche de synthèse et dans le formulaire d'édition d'un contact fonctionne mieux maintenant

**Comment by dev-allinappli** [comment]
mes tests sont tous positifs
