### ISSUE TITLE
Erreur lors de la saisie du premier caractère 

### ISSUE THREAD

**Issue by dev-allinappli** [allinappli/frenchCodePost-civicrm#10]
Quand on saisi un ou deux caractères suivis d'un espace vide, le message 'Erreur de chargement des données' apparaît.

![image](https://github.com/user-attachments/assets/1ba04f9d-0654-4130-80cf-b6b933c39be7)
![image](https://github.com/user-attachments/assets/98524331-6b30-407a-b5d9-94588f99dee1)

![image](https://github.com/user-attachments/assets/a4f272fd-8e63-4b5a-8a29-65c0dad09c38)

Comportement normal à partir de 3 caractères

![image](https://github.com/user-attachments/assets/a30b42f0-87cb-48c1-ade2-905a742d7a9f)

Il faudrait soit la désactiver pour ne laisser que l'API annoncer l'absence de données soit changer le message en invitant à saisir plus de données.

![image](https://github.com/user-attachments/assets/ba8192ba-7d75-41da-a9d4-49cb774dbd89)

Je penche d'ailleurs plus pour changer le message et remplacer le texte d'erreur par un texte invitant à entrer plus de caractères sans présager de la cohérence du texte saisi, avec les départements d'outre-mer il peut y avoir des noms d'adresse bizarres

**Comment by wyde22** [comment]
le plus simple est d'effectivement changer le message d'erreur. Par exemple est ce que cela te convient ?
![TEST-–-dewy2-dev-inoede-symbiodev-xyz-09-30-2024_05_52_PM](https://github.com/user-attachments/assets/15eb895e-67fb-4901-bce6-92e2defe20b1)

**Comment by dev-allinappli** [comment]
on peut faire tout simple non ? : `Saisissez plus de caractères` ou `Saisissez plus de lettres ou de chiffres`

**Comment by wyde22** [comment]
ok je viens de faire le changement en utilisant ta proposition soit Saisissez plus de caractères

**Comment by dev-allinappli** [comment]
fixé. sur la standalone, cela apparaît même avec un code couleur

![image](https://github.com/user-attachments/assets/e95967ce-5cde-431d-a1f7-11a7d4911c06)
