### ISSUE TITLE
nouveau champ complément d'adresse 1

### ISSUE THREAD

**Issue by dev-allinappli** [allinappli/frenchCodePost-civicrm#7]
peux-tu ajouter le complément d'adresse (1) par défaut dans le profil même si l'extension ne l'utilise pas.
Quoique il faudrait être sûr que ce champ n'est pas exposé dans l'API pour les lieux-dits

**Comment by wyde22** [comment]
je viens d'ajouter le nouveau champ complément d'adresse. Je l'ai encapsulé dans le managed et pushé sur master

**Comment by dev-allinappli** [comment]
je valide. merci
