### ISSUE TITLE
nom

### ISSUE THREAD

**Issue by dev-allinappli** [allinappli/frenchCodePost-civicrm#8]
harmoniser le nom de l'extension et du dossier (donc changer le nom du répertoire Git si possible aussi) pour :

**Comment by dev-allinappli** [comment]
nom de l'extension changé

**Comment by wyde22** [comment]
> nom de l'extension changé

tu as changé le nom de l'extension ?
sinon je comptais faire comme ceci : 
- recréer une extension avec civix et le bon nom
- ensuite mettre le code dans la nouvelle extension correctement nommée
- pushé le code de la nouvelle extension dans le repo actuel...ou bien dans un nouveau repo. A voir

**Comment by dev-allinappli** [comment]
je pense que c'est possible de la récréer ainsi dans Civix et de la pusher dans cette extension (quitte à passer par une branche avant de fusionner les branches)

**Comment by dev-allinappli** [comment]
j'ai une erreur bizarre là 

`Error loading module file (/var/www/vhosts/testwpcivi.appli.in/httpdocs/wp-content/uploads/civicrm/ext/frenchCodePost-civicrm/frenchpostcodes/frenchcodepostaux.php). Please restore the file or disable the module.`

**Comment by dev-allinappli** [comment]
il cherche une arborescence bizarre

**Comment by wyde22** [comment]
j'ai utilisé civix pour recréer une extension sur une instance de test. ensuite j'ai rapatrié les fichiers modifiés avec le bon nom dans la bonne arborescence présent sur ta plateforme. J'ai fait une batterie de test avec succès

> Error loading module file (/var/www/vhosts/testwpcivi.appli.in/httpdocs/wp-content/uploads/civicrm/ext/frenchCodePost-civicrm/frenchpostcodes/frenchcodepostaux.php). Please restore the file or disable the module.

oui pour cette erreur j'avais poussé par inadvertance la nouvelle arbo dans l'extension. j'ai corrigé l'arbo

**Comment by dev-allinappli** [comment]
terminé
