### ISSUE TITLE
Exposition du champ dans le résumé de contact

### ISSUE THREAD

**Issue by dev-allinappli** [allinappli/frenchCodePost-civicrm#9]
il est possible et c'est cohérent de modifier dans le BO l'adresse qui a été saisie via le profil en ligne, cependant l'affichage dans la fiche du contact peut prêter à confusion. 

![image](https://github.com/user-attachments/assets/3c081c13-de76-4b40-ac01-9132cd75e908)

![image](https://github.com/user-attachments/assets/8e7bdc6d-007a-4620-9195-86e80398eb99)

Il faudrait probablement masquer le champs API BAN qui en plus n'est pas vraiment éditable. Il sert juste à enregistrer une valeur.

![image](https://github.com/user-attachments/assets/1f44df7e-c0d6-4ef3-b42c-6a03b294b038)

**Comment by wyde22** [comment]
effectivement cela prête à confusion. Pour masquer ces champs je voulais faire cela via un hook civicrm mais c'était pas terrible. du coup j'ai créé un ficher js spécique pour masquer ces champs dans la fiche de synthèse du contact, dans le formulaire d'édition du contact de type individu et organisation. J'ai pushé cela sur master

a ta dispo

**Comment by dev-allinappli** [comment]
validé !

![image](https://github.com/user-attachments/assets/74ad924f-c580-4db0-8d3f-38bf84e8fa0b)
